# CircleCI config
#
# For info about comfig.yml, visit https://circleci.com/docs/2.0/language-javascript/
#
version: 2
jobs:
  build:
    docker:
      - image: circleci/node:lts

    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run: yarn install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      - run:
          name: Run unit tests
          command: yarn test:coverage --ci --runInBand

      - run:
          name: Upload coverage report to Codecov
          command: bash ./scripts/coverage_report.sh
